'use client';
import {sessionFetch} from '@/lib/session-fetch';
import {useEffect,useState} from 'react';
export type FileState={revision:number;stage:string;evidence:{id:string;name:string;text:string;created:string}[];history:{at:string;action:string;note:string;revision:number}[]};
export default function CaseEvidence({caseId,onChange}:{caseId:string;onChange:(file:FileState)=>void}){
 const [file,setFile]=useState<FileState|null>(null),[name,setName]=useState(''),[text,setText]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;sessionFetch('/api/complaints/'+caseId+'/casefile').then(async r=>{const d=await r.json() as FileState&{error?:string};if(!r.ok)throw Error(d.error);if(active){setFile(d);onChange(d);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[caseId,onChange]);
 async function save(action:string){if(!file)return;setBusy(true);setError('');try{const r=await sessionFetch('/api/complaints/'+caseId+'/casefile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:file.revision,action,note:note||'Analyst attached supporting material for review.',...(action==='add_evidence'?{name,text}:{})})});const d=await r.json() as FileState&{error?:string};if(!r.ok)throw Error(d.error);setFile(d);onChange(d);setNote('');if(action==='add_evidence'){setName('');setText('');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="fd-next"><div className="fd-section-heading"><h3>Supporting material &amp; follow-up</h3>{file&&<span className="fd-status">Revision {file.revision} · {file.stage.replaceAll('_',' ')}</span>}</div><p>Attach the information used in your investigation. Changes invalidate the previous assessment; run it again before approval.</p>{error&&<p role="alert" className="fd-form-error">{error}</p>}{file?.evidence.map(e=><details className="fd-tool" key={e.id}><summary>{e.name}</summary><p className="fd-small">Unverified analyst-supplied material · {new Date(e.created).toLocaleString()}</p><pre>{e.text}</pre></details>)}<details className="fd-tool"><summary>Add supporting material</summary><label className="fd-reply-label">Document title<input className="fd-input" value={name} maxLength={120} onChange={e=>setName(e.target.value)} placeholder="For example: correspondence summary"/></label><label className="fd-reply-label">Relevant excerpt<textarea className="fd-reply" value={text} maxLength={12000} onChange={e=>setText(e.target.value)} placeholder="Paste the relevant text. Do not include account numbers or personal identifiers."/></label><button className="button secondary" disabled={busy||!file||!name.trim()||text.trim().length<10} onClick={()=>save('add_evidence')}>Save material</button></details><label className="fd-reply-label">Follow-up note<textarea className="fd-reply" style={{minHeight:75}} value={note} maxLength={2000} onChange={e=>setNote(e.target.value)} placeholder="What information is missing, or what has now been supplied?"/></label><div className="fd-actions"><button className="button secondary" disabled={busy||!file||note.trim().length<5} onClick={()=>save('request_information')}>Mark awaiting information</button><button className="button secondary" disabled={busy||!file||note.trim().length<5||file.stage!=='waiting_for_information'&&file.history.every(h=>h.action!=='request_information')} onClick={()=>save('resume')}>Resume investigation</button></div>{file?.history.length? <details className="fd-tool"><summary>Case changes ({file.history.length})</summary>{file.history.slice().reverse().map(h=><div className="fd-history" key={h.revision}><b>Revision {h.revision} · {h.action.replaceAll('_',' ')}</b><span>{h.note}</span><small>{new Date(h.at).toLocaleString()}</small></div>)}</details>:null}</section>;
}
