'use client';
import EscalationModel from './escalation-model';
import {sessionFetch} from '@/lib/session-fetch';
import {useState,useEffect} from 'react';
import {Activity,FlaskConical,ShieldCheck,Play,Database,BookOpen,AlertCircle} from 'lucide-react';
import type {mlReport} from '@/lib/agent/ml';
type ModelReport=typeof mlReport;
type Retrieval={id?:string;mode:string;retrieval_method?:string;case_count:number;hit_rate:number;recall:number;precision:number;mrr:number;generated_at:string;scope:string;results:{id:string;query:string;relevant:string[];retrieved:string[];passed:boolean;recall:number;improvement:string}[]};
type Monitoring={scope:string;run_count:number;completed:number;failed:number;blocked:number;p50_latency_ms:number|null;p95_latency_ms:number|null;usage:{input_tokens:number;output_tokens:number;embedding_tokens:number};cost_status:string;failures:{run_id:string;task:string;category:string;reason:string;improvement:string}[];latest_evaluations:{mode:string;case_count:number;decision_accuracy:number|null;policy_compliance:number|null;source_accuracy:number|null;tool_coverage_accuracy:number|null;scope:string}[]};
async function request<T>(path:string,body?:unknown):Promise<T>{const response=await sessionFetch('/api'+path,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const value=await response.json() as T & {error?:string};if(!response.ok)throw new Error(value.error||`HTTP ${response.status}`);return value;}
const percent=(n:number|null|undefined)=>n===null||n===undefined?'Not measured':`${(n*100).toFixed(1)}%`;
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <div className="evidence-metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
export function RetrievalPanel({mode,configured}:{mode:'rules'|'live';configured:boolean}){
 const [reports,setReports]=useState<Retrieval[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{request<Retrieval[]>('/retrieval/evaluations').then(setReports).catch(e=>setError(e.message));},[]);
 return <section className="panel op-pad op-history"><div className="evidence-heading"><div><h3><BookOpen size={18}/> Independent retrieval evaluation</h3><p className="op-muted">Measure top-3 ranking before the policy guard adds mandatory evidence. Private uploads participate in your session corpus.</p></div><button className="button secondary" disabled={busy||(mode==='live'&&!configured)} onClick={async()=>{setBusy(true);setError('');try{const r=await request<Retrieval>('/retrieval/evaluations',{mode});setReports([r,...reports]);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Evaluating…':`Evaluate ${mode==='live'?'provider semantic':'local semantic'} retrieval`}</button></div>{error&&<p role="alert">{error}</p>}{reports.map(r=><div key={r.id} className="evidence-report"><div className="evidence-heading"><h3>{r.retrieval_method||(r.mode==='live'?'Provider embeddings':'Legacy policy-mode retrieval')} · {r.case_count} labelled queries</h3><small>{new Date(r.generated_at).toLocaleString()}</small></div><div className="evidence-metrics"><Metric label="Hit@3" value={percent(r.hit_rate)} detail="At least one relevant source"/><Metric label="Recall@3" value={percent(r.recall)} detail="Macro average over queries"/><Metric label="Precision@3" value={percent(r.precision)} detail="Relevant sources / 3"/><Metric label="MRR" value={r.mrr.toFixed(3)} detail="First relevant source rank"/></div><details><summary>Inspect all query results</summary><div className="table-scroll"><table><thead><tr><th>QUERY</th><th>EXPECTED</th><th>RETRIEVED</th><th>RECALL@3</th></tr></thead><tbody>{r.results.map(c=><tr key={c.id}><td>{c.query}</td><td>{c.relevant.join(', ')}</td><td>{c.retrieved.join(', ')}</td><td>{percent(c.recall)}</td></tr>)}</tbody></table></div></details></div>)}{!reports.length&&<p className="op-muted">No retrieval benchmark has run in this session. Execute it to generate measured results.</p>}</section>;
}
export default function EvidencePanels({tab,onNavigate,onDemo,configured}:{tab:string;onNavigate:(tab:string)=>void;onDemo:(task:string)=>void;configured:boolean}){
 const [model,setModel]=useState<ModelReport|null>(null),[monitor,setMonitor]=useState<Monitoring|null>(null),[retrieval,setRetrieval]=useState<Retrieval[]>([]),[error,setError]=useState('');
 useEffect(()=>{Promise.all([request<ModelReport>('/ml/evaluation'),request<Monitoring>('/monitoring'),request<Retrieval[]>('/retrieval/evaluations')]).then(([m,o,r])=>{setModel(m);setMonitor(o);setRetrieval(r);}).catch(e=>setError(e.message));},[tab]);
 if(error)return <div className="op-alert error" role="alert">{error}</div>;
 if(!model||!monitor)return <p role="status">Loading measured evidence from the server…</p>;
 const test=model.test,base=model.baseline.test;
 const total=model.split.train.rows+model.split.validation.rows+model.split.test.rows;
 const modelMetrics=<div className="evidence-metrics"><Metric label="ROC-AUC" value={test.roc_auc.toFixed(3)} detail="Held-out temporal test"/><Metric label="Average precision" value={test.average_precision.toFixed(3)} detail={`Positive prevalence ${percent(test.positive_rate)}`}/><Metric label="F1" value={test.f1.toFixed(3)} detail="Threshold selected on validation"/><Metric label="Recall" value={percent(test.recall)} detail={`${test.positive_support} delayed-response test cases`}/></div>;
 if(tab==='Project Overview')return <>
  <section className="evidence-intro panel op-pad"><span className="eyebrow">PROJECT NOTES</span><h2>Financial complaint review</h2><p><strong>Built by Hanxi Li (Alex)</strong> — LangGraph orchestration, semantic retrieval, MCP tools, custom ML inference, evaluation and human review. AI-assisted implementation with reproducible source and explicit limits.</p><p>OpsPilot combines a LangGraph workflow, policy retrieval, database tools and a trained response-delay model. Inspect each step, test the boundaries and approve an internal recommendation.</p><div className="op-buttons evidence-actions"><button className="button primary" onClick={()=>onDemo('Review financial complaint CP-001. Use the trained response-delay model and explain its limits.')}><Play size={16}/> Open complaint demo</button><button className="button secondary" onClick={()=>onNavigate('Evaluation')}><FlaskConical size={16}/> Run evaluations</button><button className="text-button" onClick={()=>onNavigate('Architecture')}>Architecture</button><a className="text-button" href="/source/opspilot-source.zip">Download source &amp; tests</a><a className="text-button" href="/project/portfolio-case-study.md">Engineering case study</a><a className="text-button" href="/project/resume-bullets.md">Résumé versions</a><a className="text-button" href="/project/README.md">README &amp; demo guide</a><span className="op-muted">GitHub repository: not connected</span></div><div className="evidence-capabilities"><span>LangGraph</span><span>Python + scikit-learn</span><span>React</span><span>D1 database</span><span>Human review</span><span>Measured evaluation</span></div><p className="op-muted">Hosted workflow and trained ML run now. {configured?'LLM key configured; inspect Live AI executions for provider evidence.':'LLM generation and provider semantic search are not connected.'} Python/FastAPI and stdio MCP are included in the source; the hosted runtime is TypeScript Workers.</p></section>
  <div className="evidence-metrics"><Metric label="Training dataset" value={total.toLocaleString()} detail="Real public CFPB complaint records"/><Metric label="Selected model" value={model.selected_model} detail={model.model_version}/><Metric label="Test ROC-AUC" value={test.roc_auc.toFixed(3)} detail="Model experiment, not Agent accuracy"/><Metric label="Your executions" value={String(monitor.run_count)} detail="Actual saved session runs"/></div>
  <div className="op-docgrid"><section className="panel op-pad"><h3>Implementation scope</h3><p>Workflow design, safe database tools, artifact packaging, model evaluation, runtime tracing, regression tests and approval concurrency controls.</p><p className="op-muted">AI-assisted implementation; engineering choices, test evidence and limitations are documented in the source. Business order fixtures are synthetic; model training uses public historical complaint data.</p><button className="text-button" onClick={()=>onNavigate('ML Model')}>Inspect training &amp; test results</button></section><section className="panel op-pad"><h3><ShieldCheck size={18}/> Review controls and limitations</h3><p>The model predicts historical response delay. It does not predict fraud, refund eligibility or actual escalation. It stays in shadow mode and abstains on unsupported domains.</p><p className="op-muted">No external payment or message is sent. Clear cookies and this anonymous session becomes inaccessible. This demonstration is not a production compliance certification.</p><button className="text-button" onClick={()=>onNavigate('Failure Analysis')}>Inspect real failure cases</button></section></div>
 </>;
 if(tab==='ML Model')return <><EscalationModel/><section className="panel op-pad"><span className="eyebrow">TRAINED MODEL · {model.model_version}</span><h2>Response-delay prediction</h2><p>Historical financial complaints can help investigate where manual follow-up may be needed. The learned score is recorded in the agent trace and reviewer context; it cannot authorize financial actions.</p><p className="op-muted">{model.task}</p>{modelMetrics}<div className="op-alert warning"><AlertCircle size={18}/>{model.promotion.reason}</div><h3>Reproducible experiment</h3><div className="table-scroll"><table><thead><tr><th>SPLIT</th><th>ROWS</th><th>DELAYED</th><th>PERIOD</th></tr></thead><tbody>{Object.entries(model.split).filter(([k])=>k!=='method').map(([k,g])=>{const v=g as ModelReport['split']['train'];return <tr key={k}><td>{k}</td><td>{v.rows}</td><td>{v.positives}</td><td>{v.start.slice(0,10)} – {v.end.slice(0,10)}</td></tr>})}</tbody></table></div><p className="op-muted">{model.selection}</p><h3>Baseline versus selected model</h3><div className="table-scroll"><table><thead><tr><th>MODEL</th><th>ROC-AUC</th><th>AVERAGE PRECISION</th><th>PRECISION</th><th>RECALL</th><th>F1</th></tr></thead><tbody>{[[model.baseline.algorithm,base],[model.selected_model,test]].map(([name,metric])=>{const m=metric as typeof test;return <tr key={name as string}><td>{name as string}</td><td>{m.roc_auc.toFixed(3)}</td><td>{m.average_precision.toFixed(3)}</td><td>{percent(m.precision)}</td><td>{percent(m.recall)}</td><td>{m.f1.toFixed(3)}</td></tr>})}</tbody></table></div><details><summary>Confusion matrix: actual rows, predicted columns</summary><div className="table-scroll"><table><thead><tr><th>ACTUAL / PREDICTED</th><th>ON TIME</th><th>DELAYED</th></tr></thead><tbody><tr><td>On time</td><td>{test.confusion_matrix[0][0]}</td><td>{test.confusion_matrix[0][1]}</td></tr><tr><td>Delayed</td><td>{test.confusion_matrix[1][0]}</td><td>{test.confusion_matrix[1][1]}</td></tr></tbody></table></div></details><h3>Features available before response</h3><p>{model.features.join(' · ')}</p><p className="op-muted">{model.dataset.excluded} {model.dataset.sampling}</p><a className="text-button" href={model.dataset.source_url} target="_blank" rel="noreferrer">CFPB source &amp; data limitations</a><p className="op-muted">Data SHA256: {model.dataset.sha256}</p><button className="button primary" onClick={()=>onDemo('Review financial complaint CP-001 and run its response-delay prediction.')}><Play size={16}/> Open model-backed workflow</button></section></>;
 if(tab==='Monitoring')return <><div className="evidence-metrics"><Metric label="Completed" value={String(monitor.completed)} detail="Awaiting review, approved or rejected"/><Metric label="Failures / blocked" value={`${monitor.failed} / ${monitor.blocked}`} detail="Recorded execution states"/><Metric label="p50 latency" value={monitor.p50_latency_ms===null?'Not measured':`${monitor.p50_latency_ms} ms`} detail="End-to-end, includes retrieval/tools"/><Metric label="p95 latency" value={monitor.p95_latency_ms===null?'Not measured':`${monitor.p95_latency_ms} ms`} detail="Measured session sample"/></div><section className="panel op-pad"><h3><Activity size={18}/> Runtime scope and cost</h3><p>{monitor.scope}</p><pre>{JSON.stringify(monitor.usage,null,2)}</pre><p>{monitor.cost_status}</p><p className="op-muted">Model {model.model_version} · shadow-only · dataset {model.dataset.sha256.slice(0,12)}. Per-node durations and statuses appear in each execution trace. Refresh this page to reload measurements.</p>{monitor.latest_evaluations.map((e,i)=><div className="evidence-report" key={i}><h3>{e.mode} · {e.case_count} cases</h3><p>Decision {percent(e.decision_accuracy)} · Policy compliance {percent(e.policy_compliance)} · Citation coverage {percent(e.source_accuracy)} · Tool coverage {percent(e.tool_coverage_accuracy)}</p><small>{e.scope}</small></div>)}</section></>;
 if(tab==='Failure Analysis')return <><div className="op-alert warning"><AlertCircle size={18}/>Failures below come from recorded runs, retrieval tests and held-out model predictions. They are not invented examples.</div><section className="panel op-pad"><h3>Execution failures and evidence blocks</h3>{monitor.failures.map(f=><details className="evidence-failure" key={f.run_id}><summary>{f.category} · {f.task}</summary><p>{f.reason}</p><p className="op-muted">Next step: {f.improvement}</p></details>)}{!monitor.failures.length&&<p className="op-muted">No failed or blocked run in this session. The missing-order demo produces a genuine evidence block.</p>}<button className="button secondary" onClick={()=>onDemo('Review refund for missing order NS-9999.')}>Open missing-evidence demo</button></section><section className="panel op-pad op-history"><h3>Retrieval misses</h3>{retrieval.flatMap(r=>r.results.filter(c=>!c.passed).map(c=><details className="evidence-failure" key={`${r.id}-${c.id}`}><summary>{r.mode} · {c.id} · {c.query}</summary><p>Expected {c.relevant.join(', ')}. Retrieved {c.retrieved.join(', ')}. Recall@3 {percent(c.recall)}.</p><p className="op-muted">{c.improvement}</p></details>))}{!retrieval.length&&<p className="op-muted">Run independent retrieval evaluation to inspect actual misses.</p>}</section><section className="panel op-pad op-history"><h3>Held-out ML classification errors</h3><p className="op-muted">Showing up to 12 high-confidence mistakes from the temporal test set. Feature values are structured public data, without narrative or personal details.</p>{model.failure_cases.map((f,i)=><details className="evidence-failure" key={i}><summary>{f.category} · public record {f.record_id}</summary><p>Actual delay: {String(f.actual_delay)} · Predicted delay: {String(f.predicted_delay)} · Estimated probability {percent(f.probability)}</p><pre>{JSON.stringify(f.features,null,2)}</pre><p className="op-muted">{f.improvement}</p></details>)}</section></>;
 return null;
}
