'use client';
import {sessionFetch} from '@/lib/session-fetch';
import { useState,useEffect,useCallback } from 'react';
import { Activity,Play,Database,FlaskConical,ClipboardCheck,GitBranch,ArrowUpRight,ShieldCheck,RefreshCw,Download,Menu,CheckCircle2,AlertCircle,Terminal,BookOpen,ChevronRight } from 'lucide-react';
import SemanticResults from './semantic-results';
import BenchmarkSummary from './benchmark-summary';
import ReleasePanel from './release-panel';
import ComplaintDesk from './complaint-desk';
import EvidencePanels,{RetrievalPanel} from './evidence-panels';
import type { State,Document } from '@/lib/agent/types';
type Run={id:string;task:string;mode:'live'|'rules';status:string;state:State;revision:number;created:string};
type Event={id:number;node:string;body:unknown;created:string};
type Health={model_configured:boolean;model:string;database:string;runtime:string};
type Batch={id:string;mode:string;created:string;results:{case_id:string;run_id:string;passed:boolean;checks?:Record<string,boolean>;latency_ms?:number;error?:string}[]};
type Action={id:string;run_id:string;body:{decision:string;amount:number;customer_reply:string};created:string};
async function api<T>(path:string,body?:unknown):Promise<T>{const r=await sessionFetch('/api'+path,{credentials:'same-origin',cache:'no-store',...(body!==undefined?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await r.json() as T & {error?:string};if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data;}
function download(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
const tabs=[['Casework',ClipboardCheck],['Project Overview',Activity],['ML Model',Database],['Failure Analysis',AlertCircle],['Monitoring',Activity],['Release evidence',GitBranch],['Agent Playground',Play],['Knowledge Base',Database],['Evaluation',FlaskConical],['Audit & Actions',ClipboardCheck],['Architecture',GitBranch]] as const;
export default function Console(){
 const [searchMode,setSearchMode]=useState<'rules'|'keyword'|'live'>('rules');
 const [suite,setSuite]=useState('complaints'),[tab,setTab]=useState<string>('Casework'),[mobile,setMobile]=useState(false),[health,setHealth]=useState<Health|null>(null),[runs,setRuns]=useState<Run[]>([]),[run,setRun]=useState<Run|null>(null),[events,setEvents]=useState<Event[]>([]),[task,setTask]=useState('Review refund for order NS-1042. Explain the policy evidence and draft a reply.'),[mode,setMode]=useState<'live'|'rules'>('rules'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reply,setReply]=useState(''),[docs,setDocs]=useState<(Document&{indexed?:boolean})[]>([]),[query,setQuery]=useState('Gold member refund window'),[search,setSearch]=useState<Document[]|null>(null),[batches,setBatches]=useState<Batch[]>([]),[actions,setActions]=useState<Action[]>([]),[uploadName,setUploadName]=useState(''),[uploadText,setUploadText]=useState('');
 const refresh=useCallback(async()=>{const [h,r]=await Promise.all([api<Health>('/health'),api<Run[]>('/runs')]);setHealth(h);setRuns(r);},[]);
 useEffect(()=>{Promise.all([api<Health>('/health'),api<Run[]>('/runs')]).then(([h,r])=>{setHealth(h);setRuns(r);}).catch(e=>setError(e.message));},[]);
 const selectRun=useCallback(async(id:string)=>{const [r,e]=await Promise.all([api<Run>('/runs/'+id),api<Event[]>('/runs/'+id+'/events')]);setRun(r);setEvents(e);setReply(r.state.reviewed_reply||r.state.answer?.customer_reply||'');},[]);
 const runId=run?.id,runStatus=run?.status;
 useEffect(()=>{if(!runId||!runStatus||!['queued','running'].includes(runStatus))return;const timer=setInterval(()=>{selectRun(runId).catch(e=>setError(e.message));},1200);return()=>clearInterval(timer);},[runId,runStatus,selectRun]);
 useEffect(()=>{if(tab==='Knowledge Base')api<(Document&{indexed?:boolean})[]>('/documents').then(setDocs).catch(e=>setError(e.message));if(tab==='Evaluation')api<Batch[]>('/evaluations').then(setBatches).catch(e=>setError(e.message));if(tab==='Audit & Actions')api<Action[]>('/actions').then(setActions).catch(e=>setError(e.message));},[tab]);
 async function execute(){setBusy(true);setError('');setNotice('');try{const r=await api<Run>('/runs',{task,mode});setRun(r);setEvents([]);setReply('');const done=await api<Run>('/runs/'+r.id+'/execute',{});setRun(done);setReply(done.state.answer?.customer_reply||'');setEvents(await api<Event[]>('/runs/'+r.id+'/events'));await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function review(decision:'approve'|'reject'){if(!run)return;setBusy(true);setError('');try{const r=await api<Run>('/runs/'+run.id+'/review',{decision,revision:run.revision,answer:reply});setRun(r);setEvents(await api<Event[]>('/runs/'+r.id+'/events'));setNotice(decision==='approve'?'Approved and saved. One internal support action was created. No payment was sent.':'Rejected and recorded in the audit log.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function evaluate(){setBusy(true);setError('');try{const cases=await api<{id:string}[]>('/dataset?scope='+suite);const b=await api<Batch>('/evaluations',{mode,case_ids:(mode==='live'?cases.slice(0,3):cases).map(c=>c.id)});setBatches(prev=>[b,...prev]);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(){setBusy(true);setError('');try{await api('/documents',{name:uploadName,text:uploadText});setDocs(await api('/documents'));setUploadName('');setUploadText('');setNotice('Reference saved to your session. It cannot override trusted policies.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const allowed=mode==='rules'||!!health?.model_configured;
 const switchTab=(name:string)=>{setTab(name);setMobile(false);setError('');setNotice('');};
 return <div className="app-shell">
  {mobile&&<button className="mobile-backdrop" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}
  <aside className={'sidebar'+(mobile?' open':'')}><button className="brand" onClick={()=>switchTab('Casework')}><span className="brand-mark"><GitBranch size={24}/></span><span>OpsPilot<small className="brand-sub">COMPLAINT OPERATIONS</small></span></button><div className="workspace-switch"><span className="workspace-avatar">F</span><span>Financial Services<small>Demonstration workspace</small></span></div><p className="nav-heading">WORKSPACE</p><nav>{tabs.map(([label,Icon])=><button key={label} className={'nav-item '+(tab===label?'active':'')} onClick={()=>switchTab(label)}><Icon size={18}/>{label==='Project Overview'?'Engineering':label==='Agent Playground'?'Workflow lab':label==='ML Model'?'Model validation':label==='Failure Analysis'?'Exceptions':label==='Knowledge Base'?'Policy library':label}{tab===label&&<ChevronRight className="nav-shortcut" size={14}/>}</button>)}</nav><div className="sidebar-bottom"><div className="guardrail"><ShieldCheck size={18}/><span>Human approval required<small>Recommendations need review</small></span></div><div className="profile"><span className="avatar">A</span><span>Alex’s portfolio<small>Persistent session workspace</small></span><span className="version">v8.0</span></div></div></aside>
  <div className="main-shell"><header className="topbar"><div className="breadcrumbs"><button className="icon-button mobile-toggle" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu/></button><span>Workspace</span><ChevronRight size={13}/><strong>{tab}</strong></div><div className="topbar-right"><span className={'connection '+(health?'connected':'')}><i/>{health?'Server connected':'Connecting'}</span><button className="text-button" onClick={()=>refresh().catch(e=>setError(e.message))}><RefreshCw size={14}/> Refresh</button></div></header>
  <main>{tab!=='Casework'&&<div className="page-heading"><div><span className="eyebrow"><span className="tiny-bar"/> OPSPILOT / OPERATIONS</span><h1>{tab}</h1><p>Supporting records, controls and validation.</p></div></div>}
  {error&&<div className="op-alert error" role="alert"><AlertCircle size={18}/><span>{error}</span><button className="icon-button" onClick={()=>setError('')}>×</button></div>}{notice&&<div className="op-alert" role="status"><CheckCircle2 size={18}/>{notice}</div>}
  {tab!=='Casework'&&!health?.model_configured&&health&&<div className="op-alert warning"><AlertCircle size={19}/><div><strong>Hosted LLM is not connected · trained ML is available</strong><p>Local workflows and the trained complaint model run on this server. Live generation and provider embeddings still require a configured server key.</p></div></div>}
  {tab==='Release evidence'&&<ReleasePanel/>}
  {tab==='Casework'&&<ComplaintDesk configured={!!health?.model_configured} onRefresh={refresh} onNavigate={switchTab}/>}
  {['Project Overview','ML Model','Failure Analysis','Monitoring'].includes(tab)&&<EvidencePanels tab={tab} configured={!!health?.model_configured} onNavigate={switchTab} onDemo={value=>{setTask(value);setMode('rules');switchTab(value.includes('CP-')?'Casework':'Agent Playground');}}/>}
  {tab==='Agent Playground'&&<>
   <div className="op-workspace"><section className="panel op-task"><div className="section-heading"><h3><Terminal size={17}/> New operation</h3><span className="op-tag">01 / INPUT</span></div><div className="op-pad"><label htmlFor="task">What should the agent investigate?</label><textarea id="task" value={task} maxLength={2000} onChange={e=>setTask(e.target.value)} placeholder="Review an order, refund or support ticket…"/><div className="op-examples">{[['Complaint + ML','CP-001'],['Gold refund','NS-1042'],['Risk hold','NS-1049'],['Missing order','NS-9999']].map(([label,key])=><button key={key} onClick={()=>setTask(key.startsWith('CP-')?`Review financial complaint ${key}. Use the trained response-delay model.`:`Review refund for order ${key}.`)}>{label}<ArrowUpRight size={12}/></button>)}</div><label htmlFor="mode">Execution mode</label><select id="mode" value={mode} onChange={e=>setMode(e.target.value as 'live'|'rules')}><option value="live">Live AI · model + semantic retrieval</option><option value="rules">Local policy workflow · trained ML for complaints</option></select><button className="button primary full" onClick={execute} disabled={busy||!allowed||task.trim().length<5}><Play size={16}/>{busy?'Executing…':'Run new task'}</button><p className="op-muted">Orders NS-1042–NS-1064 and ticket T001 are synthetic records. Policy time is fixed at October 7, 2026 so evaluations remain reproducible.</p></div></section>
   <section className="panel"><div className="section-heading"><h3><Activity size={17}/> Execution trace</h3>{run&&<span className="op-tag">{run.status.replaceAll('_',' ')}</span>}</div><div className="op-trace">{events.length?events.map((e,i)=><details key={e.id}><summary><span className="op-step">{String(i+1).padStart(2,'0')}</span><div><strong>{e.node.replaceAll('_',' ')}</strong><small>{new Date(e.created).toLocaleTimeString()+' · '+(run?.state.timings?.find(t=>t.node===e.node)?.duration_ms??0)+' ms'}</small></div><CheckCircle2 size={16}/></summary><pre>{JSON.stringify(e.body,null,2)}</pre></details>):<div className="op-empty"><GitBranch size={34}/><h3>Every step leaves evidence</h3><p>Submit a new task to inspect planning, retrieval, tool calls, evaluation and approval.</p></div>}</div>{run?.status==='queued'&&!busy&&<div className="op-pad"><button className="button primary" onClick={async()=>{setBusy(true);try{await api('/runs/'+run.id+'/execute',{});await selectRun(run.id);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Resume queued task</button></div>}{run&&<div className="op-trace-meta"><span>{run.mode==='live'?'LLM + WORKFLOW':run.state.ml_prediction?'TRAINED ML + WORKFLOW':'POLICY WORKFLOW'}</span><span>{run.state.latency_ms??0} ms</span><span>{(run.state.usage?.input_tokens||0)+(run.state.usage?.output_tokens||0)} model tokens</span><button className="text-button" onClick={()=>download('opspilot-run-'+run.id+'.json',{run,events})}><Download size={13}/> Export</button></div>}</section></div>
   {run?.state.error&&<div className="op-alert error" role="alert">{run.state.error}</div>}
   {run?.state.ml_prediction&&<section className="panel op-pad op-history"><h3>Trained model output · {run.state.ml_prediction.model_version}</h3><pre>{JSON.stringify(run.state.ml_prediction,null,2)}</pre></section>}
   {run?.state.answer&&<div className="op-result panel"><section className="op-pad"><div className="op-result-head"><span className="eyebrow">EVIDENCE-BASED RECOMMENDATION</span><span className="op-tag">{run.state.answer.decision.toUpperCase()}</span></div><h2>{run.state.answer.amount?`$${run.state.answer.amount.toFixed(2)} USD`:'Review outcome'}</h2><p>{run.state.answer.explanation}</p><div className="op-checks">{run.state.checks?.map(c=><span key={c.name} className={c.passed?'':'failed'}>{c.passed?<CheckCircle2 size={14}/>:<AlertCircle size={14}/>} {c.name}</span>)}</div><h3>Policy evidence</h3><div className="op-sources">{run.state.sources?.filter(d=>run.state.answer!.citations.includes(d.id)).map(d=><details key={d.id}><summary><BookOpen size={14}/>{d.name}<span>{d.trusted?'Trusted':'Reference'}</span></summary><p className="fd-small">{d.chunks?.length||1} chunks · {d.embedding_status||'Local embeddings available'} · updated {d.created.slice(0,10)}</p>{d.chunks?.map(c=><details key={c.id}><summary>{c.id} · {c.section}</summary><pre>{c.text}</pre></details>)||<pre>{d.body}</pre>}</details>)}</div></section><section className="op-review"><h3><ShieldCheck size={17}/> Human review</h3><p className="op-muted">Edit the reply, then approve or reject. Approval saves an internal recommendation; it does not issue a payment or send a message.</p><label htmlFor="reply">Customer reply draft</label><textarea id="reply" value={reply} onChange={e=>setReply(e.target.value)} disabled={run.status!=='awaiting_review'}/><div className="op-buttons"><button className="button primary" onClick={()=>review('approve')} disabled={busy||run.status!=='awaiting_review'||reply.trim().length<10}>Approve & save</button><button className="button secondary" onClick={()=>review('reject')} disabled={busy||run.status!=='awaiting_review'}>Reject</button></div></section></div>}
   <section className="panel op-history"><div className="section-heading"><h3>Saved runs</h3><span className="subtle">Your current browser session · {runs.length} records</span></div><div className="table-scroll"><table><thead><tr><th>TASK</th><th>MODE</th><th>STATUS</th><th>CREATED</th><th/></tr></thead><tbody>{runs.slice(0,12).map(r=><tr key={r.id}><td><strong className="task-title">{r.task}</strong><small>{r.id.slice(0,8)}</small></td><td>{r.mode==='live'?'Live AI':'Rules'}</td><td><span className="op-tag">{r.status.replaceAll('_',' ')}</span></td><td>{new Date(r.created).toLocaleString()}</td><td><button className="text-button" onClick={()=>selectRun(r.id).catch(e=>setError(e.message))}>Inspect <ArrowUpRight size={14}/></button></td></tr>)}</tbody></table>{!runs.length&&<div className="op-empty compact">No stored runs yet. Your first execution will appear here.</div>}</div></section>
  </>}
  {tab==='Knowledge Base'&&<><SemanticResults/><div className="op-workspace"><section className="panel op-pad"><h3>Search policy evidence</h3><p className="op-muted">Local semantic search runs an open-source English embedding model on this server. No API key or paid model call is required. Keyword search remains available for comparison.</p><label htmlFor="search">Query</label><input id="search" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Search mode" value={searchMode} onChange={e=>setSearchMode(e.target.value as 'rules'|'keyword'|'live')}><option value="rules">Semantic search · local model · no API</option><option value="keyword">Keyword baseline</option><option value="live">Provider embeddings · requires API</option></select><button className="button primary" disabled={busy||(searchMode==='live'&&!health?.model_configured)} onClick={async()=>{setBusy(true);setError('');try{const r=await api<{sources:Document[]}>('/search',{query,mode:searchMode});setSearch(r.sources);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Search documents</button></section><section className="panel op-pad"><h3>Add private reference</h3><p className="op-muted">References persist in your session. They cannot change the trusted refund or risk rules.</p><input aria-label="Document name" placeholder="Document name" value={uploadName} onChange={e=>setUploadName(e.target.value)}/><textarea aria-label="Reference content" placeholder="Paste reference text (20–16,000 characters)" value={uploadText} onChange={e=>setUploadText(e.target.value)}/><button className="button secondary" disabled={busy||!uploadName||uploadText.trim().length<20} onClick={upload}>Save reference</button></section></div><div className="op-docgrid">{(search||docs).map(d=><details className="panel op-pad" key={d.id}><summary><BookOpen size={18}/><strong>{d.name}</strong><span className="op-tag">{d.trusted?'Trusted policy':'Private reference'}</span></summary><p className="op-muted">{d.score!==undefined?`Relevance ${d.score.toFixed(3)}`:''}</p><p className="fd-small">{d.chunks?.length||1} chunks · {d.embedding_status||'Local embeddings available'} · updated {d.created.slice(0,10)}</p>{d.chunks?.map(c=><details key={c.id}><summary>{c.id} · {c.section}</summary><pre>{c.text}</pre></details>)||<pre>{d.body}</pre>}</details>)}</div></>}
  {tab==='Evaluation'&&<><BenchmarkSummary/><RetrievalPanel mode={mode} configured={!!health?.model_configured}/><section className="mission-panel op-evalhero"><div><span className="light-label">MEASURE THE SYSTEM YOU ACTUALLY RUN</span><h2>Test the boundaries.<br/>Inspect the failures.</h2><p>Decision, amount, evidence, tool coverage and guardrails are checked against a fixed golden dataset.</p></div><div><select aria-label="Evaluation suite" value={suite} onChange={e=>setSuite(e.target.value)}><option value="complaints">Financial complaints · 30 cases</option><option value="legacy">Legacy refunds · 30 cases</option></select><select aria-label="Evaluation mode" value={mode} onChange={e=>setMode(e.target.value as 'live'|'rules')}><option value="live">Live AI · 3 cases</option><option value="rules">Policy workflow + trained model</option></select><button className="button secondary" disabled={busy||!allowed} onClick={evaluate}><FlaskConical size={16}/>{busy?'Evaluating…':'Run evaluation now'}</button></div></section><p className="op-muted">Rules results measure policy and workflow correctness. Both modes use semantic retrieval. Only Live AI includes provider-generated answers. Neither is a production accuracy claim.</p>{batches.map(b=><section className="panel op-history" key={b.id}><div className="section-heading"><div><h3>{b.results.filter(r=>r.passed).length} / {b.results.length} passed · {b.mode==='live'?'Live AI':'Rules engine'}</h3><p>{new Date(b.created).toLocaleString()}</p></div><button className="button secondary compact" onClick={()=>download('opspilot-evaluation-'+b.id+'.json',b)}><Download size={14}/> Export JSON</button></div><div className="table-scroll"><table><thead><tr><th>CASE</th><th>RESULT</th><th>CHECKS</th><th>LATENCY</th><th/></tr></thead><tbody>{b.results.map(r=><tr key={r.case_id}><td>{r.case_id}</td><td>{r.passed?'Passed':'Failed'}</td><td>{r.error||Object.entries(r.checks||{}).filter(([,v])=>!v).map(([k])=>k).join(', ')||'All checks passed'}</td><td>{r.latency_ms??'—'} ms</td><td><button className="text-button" onClick={()=>{switchTab('Agent Playground');selectRun(r.run_id).catch(e=>setError(e.message));}}>Inspect</button></td></tr>)}</tbody></table></div></section>)}{!batches.length&&<div className="op-empty"><FlaskConical size={32}/><h3>No evaluation has run in this session</h3><p>Results appear only after the server executes the selected cases.</p></div>}</>}
  {tab==='Audit & Actions'&&<><div className="op-alert"><ShieldCheck size={18}/>Approval uses a database transaction and revision check. Every run can create at most one internal action.</div>{actions.map(a=><section className="panel op-pad op-history" key={a.id}><div className="op-result-head"><h3>{a.body.decision} · ${a.body.amount.toFixed(2)}</h3><span className="op-tag">SAVED ACTION</span></div><p>{a.body.customer_reply}</p><p className="op-muted">{new Date(a.created).toLocaleString()} · {a.run_id}</p><button className="text-button" onClick={()=>{switchTab('Agent Playground');selectRun(a.run_id).catch(e=>setError(e.message));}}>Open full audit trail <ArrowUpRight size={14}/></button></section>)}{!actions.length&&<div className="op-empty"><ClipboardCheck size={32}/><h3>No approved actions yet</h3><p>Run a task and approve its recommendation to create a durable action.</p></div>}</>}
  {tab==='Architecture'&&<><section className="architecture-hero"><span className="eyebrow">BUILT TO BE EXAMINED</span><h2>From a request<br/>to a reviewable decision.</h2><p>A server-side LangGraph workflow reads policies and business records, calls bounded tools, validates the result, and pauses for a human decision. Each step is stored in a relational database.</p><div className="tech-tags">{['React + Next.js / Vinext','LangGraph TypeScript','Cloudflare Workers','D1 / SQLite','OpenAI structured outputs','Provider embeddings (connection pending)','Trained complaint model'].map(x=><span key={x}>{x}</span>)}</div></section><div className="architecture-grid"><section className="panel op-pad"><h3>Execution path</h3>{[['01','Planner','Rules parser or structured LLM intent; explicit record IDs and allowlisted tools'],['02','Retrieval','Overlapping text chunks + vectors + trusted policy evidence'],['03','Tools','Read order/customer/ticket or financial complaint; calculate policy result'],['04','ML inference','Run the trained artifact for supported complaint records; abstain outside its domain'],['05','Answer','Structured recommendation with source citations'],['06','Evaluator','Deterministic checks; at most one model revision'],['07','Human review','Atomic review, single internal action']].map(([n,title,detail])=><div className="op-archrow" key={n}><span className="op-step">{n}</span><div><strong>{title}</strong><p className="op-muted">{detail}</p></div></div>)}</section><section className="panel op-pad"><h3>Engineering boundaries</h3><div className="op-archrow"><ShieldCheck/><p>Visitors receive an opaque HttpOnly session cookie. Runs, uploads, reviews and evaluation results are scoped to that session.</p></div><div className="op-archrow"><Database/><p>The hosted version uses D1 and exact cosine similarity over a small policy corpus. The accompanying Python project has FastAPI, LangGraph and a PostgreSQL/pgvector path.</p></div><div className="op-archrow"><Activity/><p>Live mode has no recorded fallback. Provider failures become failed runs. Model tokens are reported from provider responses; dollar cost remains unestimated.</p></div><div className="op-archrow"><ClipboardCheck/><p>Order data is synthetic. Complaint replays use public historical CFPB categories. Approval records a support recommendation, not a payment. The fixture date is fixed for reproducible evaluation.</p></div><a className="button secondary" href="/api/health" target="_blank" rel="noreferrer">Inspect server health <ArrowUpRight size={14}/></a></section></div></>}
  <footer><span>OpsPilot · Evidence before action</span><span>Server persistence · Synthetic business records · Human-controlled writes</span></footer></main></div></div>;
}
