import json,copy,datetime
from pathlib import Path
r=Path(__file__).resolve().parents[1];base=json.loads((r/'lib/agent/demo-complaints.json').read_text())[:6];first=copy.deepcopy(base[0]);extras=['Vulnerable customer escalation','Refund outside policy window','VIP customer exception','Missing evidence','Duplicate charge','Subscription cancellation dispute'];base[0]['title']='High-value refund with conflicting evidence';base[0]['summary']='Emma Chen disputes a $1,250 transaction and says the service was never delivered. The merchant supplies a completion record; the customer disputes its signature.'
for i,title in enumerate(extras,107):
 c=copy.deepcopy(first);c.update(id=f'CP-{i}',title=title,summary=f'Synthetic {title.lower()} scenario requiring documented policy review.');base.append(c)
customers=[];transactions=[];accounts=[]
for i,c in enumerate(base):
 number=101+i;amount=[1250,180,40,700,0,230,450,90,300,210,85,60][i];vulnerable=i in [0,6];fraud=i==3;missing=i==9;conflict=i==0;age=[21,12,4,5,1,3,8,65,40,15,2,20][i]
 customer={'id':f'FC-{number}','synthetic':True,'name':'Emma Chen' if i==0 else ['Alex Morgan','Sam Rivera','Taylor Brooks','Jordan Lee','Casey Quinn','Riley Chen','Avery Patel','Morgan Blake','Jamie Park','Robin Bell','Drew Scott'][i-1],'tier':'Gold' if i in [0,8] else 'Standard','previous_complaints':2 if i==0 else i%4,'vulnerability_flag':vulnerable,'previous_escalations':int(i in [0,3]),'resolution_attempts':i%4,'account_id':f'AC-{number}'}
 tx={'id':f'TX-{number}','synthetic':True,'customer_id':customer['id'],'account_id':customer['account_id'],'amount':amount,'currency':'USD','date':(datetime.date(2026,10,7)-datetime.timedelta(days=age)).isoformat(),'age_days':age,'merchant':'Demo Services Ltd','merchant_evidence':'Signed completion record supplied' if conflict else 'Receipt and service record supplied' if not missing else 'Not supplied','customer_evidence':'Customer disputes signature and delivery' if conflict else 'Complaint statement received','evidence_complete':not missing,'conflicting_evidence':conflict,'fraud_flag':fraud}
 c.update(customer_id=customer['id'],transaction_id=tx['id'],account_id=customer['account_id'],amount=amount,currency='USD',date='2026-10-07',risk_level='High' if vulnerable or fraud or conflict else 'Medium' if missing else 'Low',sample_status='awaiting_review' if i in [1,2] else 'approved' if i in [4,5] else 'unassessed',evidence=[{'id':f'EV-{number}-1','name':'Customer statement','text':c['summary'],'status':'synthetic unverified statement'},{'id':f'EV-{number}-2','name':'Merchant record','text':tx['merchant_evidence'],'status':'synthetic disputed evidence' if conflict else 'synthetic reference'}],expected_policies=['complaint_triage','fin_evidence']+(['fin_vulnerable'] if vulnerable else [])+(['fin_fraud'] if fraud else [])+(['fin_refund'] if not (vulnerable or fraud) else []),history=[{'date':'2026-10-07','action':'Synthetic fixture created','actor':'Demo seed'}]+([{'date':'2026-10-07','action':'Example prior review completed (fixture, not a live user action)','actor':'Synthetic reviewer'}] if i in [4,5] else []))
 customers.append(customer);transactions.append(tx);accounts.append({'id':customer['account_id'],'synthetic':True,'customer_id':customer['id'],'status':'demo_active','type':'Demonstration account','sensitive_details':'No real account number retained'})
(r/'lib/agent/demo-complaints.json').write_text(json.dumps(base,indent=2));(r/'lib/agent/financial-records.json').write_text(json.dumps({'financial_customers':customers,'financial_transactions':transactions,'financial_accounts':accounts},indent=2))
policies=[('fin_refund','Financial Refund Review','3.1','Complete and non-conflicting evidence is required. Standard requests beyond 30 days are not eligible for a refund recommendation; Gold requests have a 45-day exception. Amounts above USD 1,000 require specialist escalation. All recommendations require human approval; no automatic payment.'),('fin_evidence','Evidence Requirements','4.2','Read the complaint, linked customer, transaction and account. Missing or mismatched records block recommendations. A customer statement conflicting with a merchant record requires escalation and further investigation. Never resolve conflicting evidence solely from a model probability.'),('fin_vulnerable','Vulnerable Customer','2.4','A recorded vulnerability flag requires specialist escalation, respectful communication and human review. Do not infer sensitive characteristics from names or complaint language.'),('fin_fraud','Fraud Review','2.1','A declared fraud suspicion flag requires specialist escalation and human review. Neither the historical response-delay model nor the synthetic escalation classifier establishes actual fraud.'),('fin_hardship','Financial Hardship','2.2','A hardship request should be referred to an authorised reviewer. Do not promise debt relief or financial entitlement. Request only the minimum relevant supporting material.'),('fin_chargeback','Chargeback Procedure','5.1','Confirm transaction ownership, amount and evidence before considering a chargeback referral. Missing evidence blocks referral preparation. No external chargeback is submitted by this demo.'),('fin_communication','Customer Communication Standard','1.2','Draft clear factual updates, identify missing evidence and state that a reviewer must confirm the recommendation. Never say money has been sent or a dispute resolved before verified action.'),('fin_privacy','Financial Privacy','1.1','Use synthetic identifiers in demonstrations. Do not expose account numbers, personal documents or another session’s data. Privacy complaints require authorised investigation.'),('fin_escalation','Specialist Escalation Guide','6.1','Escalate high-value requests above USD 1,000, vulnerability flags, fraud flags and conflicting evidence. ML scores supply shadow context only; they never override mandatory controls.')]
(r/'lib/agent/financial-policies.json').write_text(json.dumps([{'id':id,'name':name+' §'+section,'section':section,'version':'demo-1','updated':'2026-10-08','text':'Synthetic internal demonstration policy; not legal or regulatory advice.\n\n§'+section+' '+text} for id,name,section,text in policies],indent=2))
